//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FillWords.Phone._8._0.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FillWords.Phone._8._0.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RiempireParole.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category is not yet available for you...
        /// </summary>
        public static string CategoryIsNotAvailable {
            get {
                return ResourceManager.GetString("CategoryIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to collect the word differently!.
        /// </summary>
        public static string DifferentPathWord {
            get {
                return ResourceManager.GetString("DifferentPathWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estimate.
        /// </summary>
        public static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like the game?.
        /// </summary>
        public static string EstimateMessage {
            get {
                return ResourceManager.GetString("EstimateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! The game finished!!!.
        /// </summary>
        public static string GameCompleted {
            get {
                return ResourceManager.GetString("GameCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 hints.
        /// </summary>
        public static string Hints150 {
            get {
                return ResourceManager.GetString("Hints150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 hints.
        /// </summary>
        public static string Hints20 {
            get {
                return ResourceManager.GetString("Hints20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 hints.
        /// </summary>
        public static string Hints40 {
            get {
                return ResourceManager.GetString("Hints40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 hints.
        /// </summary>
        public static string Hints80 {
            get {
                return ResourceManager.GetString("Hints80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots of hints.
        /// </summary>
        public static string HintsAll {
            get {
                return ResourceManager.GetString("HintsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the connection to the Internet!.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + removing ads.
        /// </summary>
        public static string PlusRemoveAds {
            get {
                return ResourceManager.GetString("PlusRemoveAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already bought this product!.
        /// </summary>
        public static string ProductExitsts {
            get {
                return ResourceManager.GetString("ProductExitsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when buying the product: .
        /// </summary>
        public static string PurchaseError {
            get {
                return ResourceManager.GetString("PurchaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchases.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RiempireParole.
        /// </summary>
        public static string ShareMessage {
            get {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your purchase!.
        /// </summary>
        public static string ThankYouForPurchase {
            get {
                return ResourceManager.GetString("ThankYouForPurchase", resourceCulture);
            }
        }
    }
}
